### ISSUE TITLE
Please specify licence

### ISSUE THREAD

**Issue by Octochef** [antvis/G6VP#101]
Hello all,
great project, love to collaborate. But what is the licence?
I see some packages with "MIT" but others say nothing can you please put general licence specification on the github project page. Happy to contribute

**Comment by pomelo-nwu** [comment]
@Octochef I'm glad you like this product. It was incubated by Ant Group and is similar to another open source product [TuGraph](https://github.com/TuGraph-db/tugraph-db/blob/master/LICENSE), so it will use Apache 2.0. I will add LICENSE later

**Comment by Octochef** [comment]
Really great, and congratulations, i believe this will be quite impactful

**Comment by pomelo-nwu** [comment]
@Octochef Thanks for the recognition, welcome to contribute together
