### ISSUE TITLE
Feedback on  G6VP

### ISSUE THREAD

**Issue by ShunyangLi** [antvis/G6VP#113]
Dear staffs,

I am writing to express my gratitude for the fantastic product you have created. It has been a great help to me, and I appreciate all the hard work and effort that went into it.

However, I do have one question regarding the product. I was wondering if it supports undirected edges. If so, please let me know how to utilize this feature; if not, any plans for future updates?

Thank you again for your time and for creating such a wonderful product.

Best regards,
Charles

**Comment by pomelo-nwu** [comment]
@ShunyangLi 很高兴你能喜欢这个产品，undirected edges 其实是支持的。你想要的是边的样式没有箭头吗，这个暂时没有开放出来给用户配置，如果你需要，后续产品迭代，可以把箭头配置开放出来。

**Comment by ShunyangLi** [comment]
你好，

非常感谢您的回复。是的，想要边的样式不带箭头。因为一些表达如果用无向图来代替可能会更加合适。非常感谢您的考虑。

祝好，

**Comment by pomelo-nwu** [comment]
![image](https://user-images.githubusercontent.com/10703060/215258279-a8b4206d-1553-4ee1-9ddc-641acb034320.png)
@ShunyangLi 本地代码已经修复了，发布还需要几天，详见PR：https://github.com/antvis/G6VP/pull/114

**Comment by ShunyangLi** [comment]
非常感谢！

**Comment by pomelo-nwu** [comment]
@ShunyangLi 如果有帮助，还望求个Star，帮忙推广 🙏

**Comment by ShunyangLi** [comment]
没问题的！
