### ISSUE TITLE
请教一下，G6VP是否可用在windows使用? pnpm install时很多库无法安装，请问如何设置镜像仓？

### ISSUE THREAD

**Issue by ahong007007** [antvis/G6VP#119]
GET https://mirrors.xx/npm/js-tokens/download/js-tokens-4.0.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://mirrors.xx/npm/loose-envify/download/loose-envify-1.4.0.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://mirrors.xx/npm/@antv/algorithm/download/@antv/algorithm-0.1.25.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 
1 retries left.
 WARN  GET https://mirrors.xx/npm/scheduler/download/scheduler-0.20.2.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 WARN  GET https://mirrors.xx/npm/@antv/g6/download/@antv/g6-4.7.14.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.

**Comment by pomelo-nwu** [comment]
仓库不是已经设置源了么：https://github.com/antvis/G6VP/blob/master/.npmrc#L2
可以试试本地永久设置：
pnpm config set registry https://registry.npm.taobao.org
