### ISSUE TITLE
Graph导出svg文件

### ISSUE THREAD

**Issue by ShunyangLi** [antvis/G6VP#127]
您好,

请问G6VP现在支持导出svg文件么?

**Comment by pomelo-nwu** [comment]
@ShunyangLi 可以使用「下载」资产，可以导出png图片，因为canvas绘制的都是位图，所以没办法到处svg矢量图
![image](https://user-images.githubusercontent.com/10703060/218006239-a2631afd-6e34-4928-83bd-67dc4c267428.png)

**Comment by ShunyangLi** [comment]
好的, 谢谢回复
