### ISSUE TITLE
添加900+的节点后 提示加载的数据量过大

### ISSUE THREAD

**Issue by yuuunagi** [antvis/G6VP#130]
添加900+的节点后提示加载的数据量过大
建议聚合数据，默认切换到网格布局。您也可以在「资产中心」中加载「大图组件」启用 3D 渲染。
这里的「大图组件」启用 3D 渲染指的是什么，找了一圈没找到， 最接近的只有一个3D大图

**Comment by pomelo-nwu** [comment]
可以加载「大图概览」资产试试
![Uploading image.png…]()

**Comment by yuuunagi** [comment]
大图概览我已经加了，并且限制到1000，结果还是会提示数据量过大
![图片](https://user-images.githubusercontent.com/51359328/218626713-1be58b61-8ea2-4d2e-9af7-2a9089da5b41.png)

**Comment by pomelo-nwu** [comment]
设置完要保存下，不知道你有没有点击右上角的保存按钮

**Comment by yuuunagi** [comment]
[4.zip](https://github.com/antvis/G6VP/files/10728510/4.zip)
这是我导出的项目, 这边已经保存展示限制1000

**Comment by pomelo-nwu** [comment]
@yuuunagi 
![image](https://user-images.githubusercontent.com/10703060/218633180-3e95e9b6-be5a-425e-ac30-3d8757c255b1.png)
已经展示出来了，可能是文案提示的bug，这个我后面修复下

**Comment by pomelo-nwu** [comment]
@yuuunagi 其实有了展示限制（比如限制400节点），可以做交互式查询分析
![image](https://user-images.githubusercontent.com/10703060/218633356-6417c331-a15f-40f4-8e4d-ffd5af7b3055.png)
如果想要看数据全貌，可以点击工具栏的「3D大图」
![image](https://user-images.githubusercontent.com/10703060/218633513-46d2a1f5-2bd6-43ea-ab4e-24d5ec4c4cb9.png)
3ds视图下面，还可以继续与筛选面板协同，看到筛选的数据，在大图中的分布
![image](https://user-images.githubusercontent.com/10703060/218633639-b9386da8-da9e-4b8c-8a10-1df40d9f923f.png)

**Comment by yuuunagi** [comment]
好的，我研究下3D大图，这边的提示麻烦修复下
