### ISSUE TITLE
big picture view properties are not loading.

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#168]
```
  "@ant-design/icons": "^4.7.0",
    "@antv/g2plot": "^2.4.16",
    "@antv/g6": "^4.7.10",
    "@antv/gi-assets-advance": "^2.0.0",
    "@antv/gi-assets-algorithm": "^1.0.0",
    "@antv/gi-assets-basic": "^2.0.1",
    "@antv/gi-assets-graphscope": "^2.0.3",
    "@antv/gi-assets-scene": "^1.0.0",
    "@antv/gi-assets-tugraph": "^2.0.0",
    "@antv/gi-sdk": "^2.0.2",
    "@antv/gi-theme-antd": "^0.3.0",
    "@antv/graphin": "^2.7.13",
    "@antv/graphin-components": "^2.4.0",
    "@antv/graphin-icons": "^1.0.0",
   "antd": "^4.24.8",
```

I just updated the dependencies above and the filter panel properties are not loading in the big picture overview. There was no such problem before updating the versions.

![Untitled](https://user-images.githubusercontent.com/52632318/224658785-7068d62f-8436-47be-9d2e-03b817816746.png)

@pomelo-nwu

**Comment by RackweLLizm** [comment]
"@antv/gi-assets-basic": "^1.2.1",

The problem is fixed when I restore to the library
@pomelo-nwu

**Comment by pomelo-nwu** [comment]
@RackweLLizm Just be consistent with the version of the exported SDK
![image](https://user-images.githubusercontent.com/10703060/227072514-0aae3df7-ac3a-44e5-8569-0ab223411bd4.png)
The 2.0 assets must correspond to the 2.0 SDK to work，2.0 assets work with the 2.0 SDK, check out this PR to learn more：https://github.com/antvis/G6VP/pull/128/files
btw："big picture view" should be a machine translation, and its correct meaning should be "the display controller of large graph"
