### ISSUE TITLE
Using "image" type as node icon

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#178]
Hello. First of all, thank you again for sharing this amazing project with us; In our project, we want to give "image" as icon to the nodes. I can do this in Graphin. graph.updateItem() on Node
Nodes don't get image property as icon type even though I make the necessary edits with . Any help on this would be very helpful for us.
![newissue](https://user-images.githubusercontent.com/52632318/228321378-5f5538b9-2d05-4fe3-bf21-2ce78da08cb2.png)

**Comment by pomelo-nwu** [comment]
@RackweLLizm Can you give me a reproduction demo, such as codesandbox, so that I can help you check the problem

**Comment by RackweLLizm** [comment]
What I want to do is add a feature, not a bug. That is, using "image" instead of font icon or text icon for the icon property of the SimpleNode type. Fonticon and texticon are supported built into the graphinsight site. But it does not allow adding photos to a Node. What I want to do is something like this.

  ```
context.graph.updateItem(id, {
           style: {
             keyshape: {
               size: 80,
               fillOpacity: 1,
             },
             icon: {
           type: 'image',
           value: 'https://avatars.githubusercontent.com/u/105033?v=4',
           visible: true,
           size: [80,80],
           clip: {
             r: 40
           }
             },
             label: {
               offset: [0, 12],
               value:(a._cfg?.model?.data as any).id
             }
           }
         })

```
When I do such an update on the graph, Node does not show the photo in the url.

It would be a nice feature to be able to show photos, if any, while people are showing their Nodes.


These are the properties that a node's icons can have in G6VP.

![github1](https://user-images.githubusercontent.com/52632318/231271665-32c121f5-a459-4070-ae97-68e9ee78c676.png)


this is what i want to do.
![github2](https://user-images.githubusercontent.com/52632318/231271698-5486c5b7-58f5-4f35-8770-ec1e49361be0.png)


When I update a node style on the context, I fail. It doesn't give an error, but it doesn't show the Photo either.

**Comment by RackweLLizm** [comment]
@pomelo-nwu 

I found the problem.

https://github.com/antvis/G6VP/blob/master/packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts

```
 if (icon.type === 'image') {
      return {
        fill: 'transparent',
        size: [keyshape.size, keyshape.size],
        clip: { r: keyshape.size / 2 },
        value: value,
      };
    }
```
this part is missing the "type:image" field. For this reason, the image icons were not rendering properly.

```
 if (icon.type === 'image') {
      return {
        fill: 'transparent',
        **### type:'image',**
        size: [keyshape.size, keyshape.size],
        clip: { r: keyshape.size / 2 },
        value: value,
      };
    }
```

**Comment by pomelo-nwu** [comment]
@RackweLLizm Thank you for finding this problem and finding a solution. Could you please give me a PR

**Comment by RackweLLizm** [comment]
https://github.com/antvis/G6VP/pull/225
