### ISSUE TITLE
The displayed ID is not consistent with the ID selected when importing the data.

### ISSUE THREAD

**Issue by bifenglin** [antvis/G6VP#195]
The displayed ID is not consistent with the ID selected when importing the data. The default display is the value in the `id` column, but the ID column selected when importing the data is `name`. Is this a bug or do I need to replace the values in the `id` column with those in the `name` column?
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/15813364/231118826-c1754670-a184-4d10-8c6b-398283edb4fc.png">
<img width="789" alt="image" src="https://user-images.githubusercontent.com/15813364/231119018-b42a5bec-0423-442f-8da8-e1302764a71e.png">

**Comment by pomelo-nwu** [comment]
@bifenglin The ID set when importing data is intended to be the index of the nodes table. When visualized, the default value of the displayed label is 「id」, but users can set it themselves. Refer to this document:https://insight.antv.antgroup.com/#/open/assets-list?assetKey=StyleSetting
