### ISSUE TITLE
[Bug] 在平台上创建的画布的侧边容器中添加集成组件会白屏

### ISSUE THREAD

**Issue by tyn1998** [antvis/G6VP#250]
Hi, G6VP团队，反馈一个不知道是不是bug的白屏问题，下面的视频是新建一个画布后马上进行侧边容器添加集成组件操作后发生的：

https://github.com/antvis/G6VP/assets/32434520/3a6a3eb6-50d0-4b6d-9ba4-dc54d0972492

控制台报错信息：

<img width="1506" alt="image" src="https://github.com/antvis/G6VP/assets/32434520/3ca3ec76-3b01-4470-9b8c-e02f6d5e0b8e">

**Comment by pomelo-nwu** [comment]
@tyn1998 是的，已知的问题，今晚修复

**Comment by pomelo-nwu** [comment]
@tyn1998 已经修复了，看下哈：https://insight.antv.antgroup.com/#/home

**Comment by tyn1998** [comment]
没错，赞~

**Comment by pomelo-nwu** [comment]
@tyn1998 你发现了华点...  刚才发布的时候顺手解决的，我刚提个PR

**Comment by pomelo-nwu** [comment]
@tyn1998 https://github.com/antvis/G6VP/invitations 邀请你加入组织！
