### ISSUE TITLE
Request for support - adding field mapping to the size property of nodes and edges

### ISSUE THREAD

**Issue by jkren2023** [antvis/G6VP#274]
Hello Team,

Firstly, I want to express my gratitude for creating an amazing open-source graph visualization library. I've been using it and I'm truly impressed by its capabilities.

I have a small request to make. Is it possible to add support for field mapping to the size property of nodes and edges? This would allow us to associate the size of nodes and edges with factors like degree or weight, enabling us to highlight important points on the graph by varying their sizes.

I would greatly appreciate it if you could consider adding this feature in the future. Thank you for your time and effort.

Best regards

**Comment by pomelo-nwu** [comment]
First of all, thank you very much for your interest in G6VP. 
"support for field mapping to the size property of nodes and edges" This can be implemented by customizing a new element asset, Now the official built-in assets "SimpleNode" and "SimpleEdge" are designed to be grouped first and then set specific styles. You can read this document for details：https://insight.antv.antgroup.com/#/open/assets-list?assetKey=StyleSetting

![image](https://github.com/antvis/G6VP/assets/10703060/db240e58-55fd-4391-9753-19b339e181c2)

We plan to build this element assets in the future, or you can implement by yourself , refer to this code: https://github.com/antvis/G6VP/blob/master/packages/gi-assets-basic/src/elements/SimpleNode/registerTransform.ts#L180

**Comment by jkren2023** [comment]
Thanks for getting back to me so quickly with a solution. I'll give it a shot and try to solve the problem myself based on your guidance. Once again, thanks a lot for your assistance. Looking forward to the continued development of G6VP.
