### ISSUE TITLE
Asset：新增 SocketQuery 资产

### ISSUE THREAD

**Issue by pomelo-nwu** [antvis/G6VP#293]
SocketQuery 是一款通用查询资产，用户可以在配置面板中填写地址，即可通过 WebSockets 进行数据交互。可以参考之前帮助「中原银行」实现的一个 Socket 资产：https://github.com/BoyYangzai/gi-assets-socket 

该资产将用于流式图计算交互展示

**Comment by Aarebecca** [comment]
Ref: https://github.com/antvis/G6VP/pull/329
