### ISSUE TITLE
Perf ：画布优化

### ISSUE THREAD

**Issue by pomelo-nwu** [antvis/G6VP#296]
- 01 「侧边栏布局」这个资产太复杂了，感觉用不太明白，发布后会带来很多的解释成本，建议放在 asf 自己的业务资产中，先从 gi 的官方资产中下架 @yangzy0603 

![image](https://github.com/antvis/G6VP/assets/10703060/580712a7-be5b-4c56-accf-866ca0db9d20)

- 02 自运行组件的 icon 修改下

![image](https://github.com/antvis/G6VP/assets/10703060/434457b3-cd1c-4be3-b62f-3df904c91f04)

- 03 提示文案修改下，现在还不够好理解

![image](https://github.com/antvis/G6VP/assets/10703060/b82c47bd-1464-4d1e-b167-93f37bd037c7)

- 04 「桑基图」资产，当加载的时候，增加文案提示：可以在配置面板中设置 xxxx

![image](https://github.com/antvis/G6VP/assets/10703060/63643582-7cff-403f-acad-faa7d87ff9fc)

- 05 「子图布局」每个布局方法的参数应该设置下，做到默认好看，现在感觉参数没调整过。同时UI样式上需要设计下，比如边框border的颜色与整体风格不搭

![image](https://github.com/antvis/G6VP/assets/10703060/fae8aed4-457c-4a48-9a1c-7e2f4844e77d)

- 06 标记节点，默认用直接打标（icon）的形式，不用出现可编辑的便贴框，这属于高级功能，可以让用户探索发现的

![image](https://github.com/antvis/G6VP/assets/10703060/5c680621-a0fc-4029-b4fa-6888d9a656a9)

- 07 「自适应」和「视图居中」现在功能重复了。需要合并成一个新资产「自适应居中」，删除之前的这俩资产，给用户更清晰明确的功能资产。

![image](https://github.com/antvis/G6VP/assets/10703060/55a72ff3-5bec-4cc8-b1e9-6d5d960b474d)

- 08 「地图模式」切换的时候，如果是没有地理数据，应该要增加一个notification 提示，引导用户检查数据是否有地理字段，或者引导用户去配置面板配置

![image](https://github.com/antvis/G6VP/assets/10703060/be740c91-87bd-4c2c-8136-745f891874a2)

- 09 「布局切换」，icon 和 title 之间需要一个间隙，同时，切换布局的时候，应该都要掉用下 fitviewCenter，不然每次切换后还得手动让它回到画布中央，太难受了
![image](https://github.com/antvis/G6VP/assets/10703060/764aa998-7a28-487c-946c-89190ba31226)

- 10 「快照画廊」现在UI太丑了，急需要设计！「新增页签」资产，可以和「多画布页签」一起上线，现在先下线

![image](https://github.com/antvis/G6VP/assets/10703060/2c8b8d79-f65b-4309-81d9-9644364f3ecb)

**Comment by Yanyan-Wang** [comment]
暂且认领2，3，5.

关于 4，一开始是只打标，点击 icon 的时候才出编辑框，但是当时业务上说直接出，所以这样设计的，先不用改吧

**Comment by pomelo-nwu** [comment]
我来 认领：4，7，8，9，10
