### ISSUE TITLE
graphviz dot format

### ISSUE THREAD

**Issue by williamfzc** [antvis/G6VP#299]
hi，很棒的项目：）

注意到20年在G6有一个类似的issue：https://github.com/antvis/G6/issues/1352
不知道在平台化之后，是否有计划对接graphviz dot格式的数据？

目前大量学术化的图都还是用graphviz渲染与表达，应该能增加不少用户。

**Comment by pomelo-nwu** [comment]
@williamfzc 感谢你的建议，产品本身是希望能够对接尽可能多的数据源，帮助到用户可以更快把数据可视化出来。
要新增这个「graphviz dot」格式的数据源，我们目前还需要几个种子用户，以此确保我们做的功能能有用户使用和反馈，如果你能提供这方面的帮助，那就太好了

**Comment by williamfzc** [comment]
> @williamfzc 感谢你的建议，产品本身是希望能够对接尽可能多的数据源，帮助到用户可以更快把数据可视化出来。 要新增这个「graphviz dot」格式的数据源，我们目前还需要几个种子用户，以此确保我们做的功能能有用户使用和反馈，如果你能提供这方面的帮助，那就太好了

@pomelo-nwu  响应速度好快~
谢谢你，因为实际工作比较忙，可能没办法成为种子用户了：（

不过，

- 我大概看了下G6VP对数据源的支持是内置在G6VP，跟平台耦合（当然我理解你们的产品需要）；
- 我的需求可能更像是将graphviz dot转换为G6能接受的JSON格式，同时可以被G6/G6VP使用；

想了下貌似也不太适合集成在此，可以看看其他人是否有类似需求再议吧~
