### ISSUE TITLE
pnpm install安装依赖失败

### ISSUE THREAD

**Issue by yikenie** [antvis/G6VP#327]
下载代码后，使用pnpm install安装依赖失败，报错信息如下：
![image](https://github.com/antvis/G6VP/assets/47709014/33b8f607-03ef-45c0-a181-b6dbec0a8c98)
![image](https://github.com/antvis/G6VP/assets/47709014/125d31a5-8fdc-4742-8526-b9aa8b169681)

**Comment by pomelo-nwu** [comment]
@yikenie 首先这个不是依赖安装包错，它是依赖安装后执行 npm run build:all:es 报的错，所以如果你想要看到具体的报错信息，需要根目录下执行 npm run build:all:es ，如果报错信息很明显，比如上图这个，可以直接进入报错的子包执行命令： cd pacakges/gi-theme-antd ，执行 npm run build:es

**Comment by pomelo-nwu** [comment]
@yikenie 可以检查下你的node版本，推荐是 node 16+

**Comment by yikenie** [comment]
npm run build:all:es显示：
![image](https://github.com/antvis/G6VP/assets/47709014/e9af5b30-879e-4265-a2a1-a26da0aff98f)
进入gi-theme-antd执行命令后显示：
![image](https://github.com/antvis/G6VP/assets/47709014/3a56975c-fcd2-423c-bd6a-7c9264ee28c2)
进入gi-common-components执行命令后显示：
![image](https://github.com/antvis/G6VP/assets/47709014/2a960db0-25e7-445b-aedf-c5cccf7ef57c)
我的node版本为：
![image](https://github.com/antvis/G6VP/assets/47709014/23cc6f31-7a83-46f6-aeae-8795a88230ed)

**Comment by pomelo-nwu** [comment]
@yikenie 如果是windows环境，看起来应该是这个问题：https://github.com/antvis/G6VP/issues/44#issuecomment-1341901665

**Comment by yikenie** [comment]
根据引用的解决办法，根据报错信息提示修改很多gi-xx文件下的tsconfig.json文件的declaration的值之后，显示如下：
![image](https://github.com/antvis/G6VP/assets/47709014/0fd9df7c-219b-4a52-aee2-1d72d03dbf13)
运行npm run start后显示：
![image](https://github.com/antvis/G6VP/assets/47709014/4573d4da-9c56-46a1-be0d-099a44dfda30)
修改gi-site的package.json文件，把umi node提前后显示：
![image](https://github.com/antvis/G6VP/assets/47709014/b8a92b02-c596-4ffa-aedf-7b496c95e3b6)
![image](https://github.com/antvis/G6VP/assets/47709014/29e778f8-e75f-4643-b3fb-4f0faeb27419)

**Comment by yikenie** [comment]
运行成功了，但是我想问一下进入network这个网址后，它提示自动进去登录界面，进入7001端口。但是7001端口
页面显示不出来，这个是啥呢
![image](https://github.com/antvis/G6VP/assets/47709014/940717b0-4862-40f2-aa88-a1599a78a5e9)

**Comment by pomelo-nwu** [comment]
@yikenie 你的代码是master的吗，感觉不像是最新的，同时，站点是 gi-site 后启动的 npm run start ，默认是8000， 代理服务是 gi-httpservices 启动后是 7001

**Comment by yikenie** [comment]
是最新的master，我最近还特地重新下载了代码，下载时间是昨天
![image](https://github.com/antvis/G6VP/assets/47709014/15d9b87f-187b-4703-beee-fcabd3bb560b)

**Comment by pomelo-nwu** [comment]
@yikenie cd gi-site 然后 npm run start 不就可以了么

**Comment by yikenie** [comment]
啊现在是可以的运行的，我就是好奇那个network，以前用的时候没看到有提示登录的消息
