### ISSUE TITLE
FilterPanel Uniqe Key 

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#334]
![filterpanel](https://github.com/antvis/G6VP/assets/52632318/eba39e02-4d81-4aac-9bd9-57b7a25738cd)

export: npm packages.

**Comment by pomelo-nwu** [comment]
@RackweLLizm  ESM 模式有点问题，我来跟进处理下：https://github.com/antvis/G6VP/issues/337

**Comment by pomelo-nwu** [comment]
@RackweLLizm Thank you for finding this problem, I reproduced the problem locally and solved it
![image](https://github.com/antvis/G6VP/assets/10703060/cfb652cc-2217-489a-aa7c-812f17541c70)

By the way, which scaffold is your project? I encountered a lot of problems with create-react-app at the beginning, but everything went well with umi

**Comment by RackweLLizm** [comment]
@pomelo-nwu  

Sorry for my delayed reply. Yes, there are great difficulties in projects created with CRA. The most important of these is that CRA does not support ".LESS" extension CSS files. I had to manually convert all the .LESS css in the source code to regular CSS.

The npm run build command also gives trouble in the CRA, I don't know if other frameworks have this problem, but I solved it like this:

  "scripts": {
     "start": "react-scripts --max_old_space_size=14096 start",
     "build": "react-scripts --max_old_space_size=14096 build",
     "serve": "serve build",
     "test": "react-scripts test",
     "eject": "react-scripts eject"
   },

I will continue to share other problems with you on this issue as I think of it.

There is also a "uniqe key" error similar to the one above in the filter panel. Clicking on the filter panel gives the following 2 errors

![bunu yolla](https://github.com/antvis/G6VP/assets/52632318/7ba781b5-974e-416f-bf8a-c4b42597dc17)

**Comment by pomelo-nwu** [comment]
@RackweLLizm It seems that you have been using G6VP since last December. Do you have any suggestions for this project？

**Comment by pomelo-nwu** [comment]
@RackweLLizm As for the project, do you also need internationalization support? We plan to do some internationalization for the project in the near future, so that non-Chinese users can use it.

**Comment by pomelo-nwu** [comment]
@RackweLLizm Thank you for your sincere advice！
G6VP is designed to be a product, not a technology library, so ideally we don't want to write technical documentation for every asset. We prefer users to ISSUE directly, and we optimize one by one. Another technology library: Graphin, is most criticized for its performance issues, as can be seen in this discussion: https://github.com/antvis/Graphin/discussions/490 

We are currently working on g6@5.0 and will also upgrade graphin to version 2.8. We hope that in the near future, the support of nodes up to 2000 will be very smooth. This will take a little time. Thank you for your patience!

- g6@5.0 alpha Experience url: https://insight.antv.antgroup.com/#/open/g6v5demo
![image](https://github.com/antvis/G6VP/assets/10703060/5c6d6358-7bce-4427-9b7f-f5c817ddb7b5)

**Comment by RackweLLizm** [comment]
@pomelo-nwu 
That was great and news that I really wanted to hear! I will be impatiently waiting.

**Comment by RackweLLizm** [comment]
@pomelo-nwu 



> @RackweLLizm As for the project, do you also need internationalization support? We plan to do some internationalization for the project in the near future, so that non-Chinese users can use it.


For now, I am trying to solve this problem with google translate. Although there are alternative projects to Graphin and G6VP, they are not as easy to understand and develop as Graphin. So there is no alternative for me. But I think that English language support is necessary in order to open up to the whole world in a global sense. Everyone should be able to understand and use this wonderful project.

In addition, there are hard-coded chinese scripts in G6VP, I had to intervene in the source codes of the library to edit them. For this, it will be extremely useful to provide Localization support and to ensure that the texts of the components can be easily changed.
