### ISSUE TITLE
项目运行后报错，怎么打开web界面

### ISSUE THREAD

**Issue by yubo0923** [antvis/G6VP#353]
@ ./src/pages/Workspace/SaveList.tsx 24:0-37 242:18-23
 @ ./src/pages/Workspace/index.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./src/services/assets.ts
Module not found: Error: Can't resolve '@antv/gi-sdk' in 'D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-site\src\services'
 @ ./src/services/assets.ts 4:0-37 20:27-32 21:23-28
 @ ./src/pages/Dataset/Create.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts

ERROR in ./src/components/Navbar/Theme.tsx
Module not found: Error: Can't resolve '@antv/gi-theme-antd' in 'D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-site\src\components\Navbar'
 @ ./src/components/Navbar/Theme.tsx 4:0-46 70:35-46
 @ ./src/components/Navbar/SiteNav.tsx
 @ ./src/layouts/index.tsx
 @ ./src/.umi/core/routes.ts
 @ ./src/.umi/umi.ts
 @ multi ./src/.umi/umi.ts
 info  如果你需要进交流群，请访问 https://fb.umijs.org
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'

以上是项目运行后的代码，运行完报错

**Comment by pomelo-nwu** [comment]
报错提示是：Can't resolve '@antv/gi-sdk' 

很显然，是不是依赖没有安装好，你按照官方文档操作下：https://github.com/antvis/G6VP/blob/master/README.md#21-%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

pnpm install

**Comment by yubo0923** [comment]
packages/gi-assets-galaxybase            |  WARN  The field "resolutions" was found in D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-assets-galaxybase/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.
packages/gi-assets-tugraph               |  WARN  The field "resolutions" was found in D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-assets-tugraph/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.
Scope: all 22 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. postinstall$ npm run build:all:es
│ > build:all:es
│ > turbo run build:es
│ Error: We detected multiple package managers in your repository: pnpm, npm. Please remove one of them.
└─ Failed in 1.9s at D:\huiding\gsitem\tugraph\ant2\G6VP
 ELIFECYCLE  Command failed with exit code 1.

我又重新下载的依赖，npm和pnpm 必须留一个嘛

**Comment by pomelo-nwu** [comment]
@yubo0923 只能使用 pnpm 安装

**Comment by yubo0923** [comment]
D:\ant2\G6VP>pnpm install
packages/gi-assets-galaxybase            |  WARN  The field "resolutions" was found in D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-assets-galaxybase/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.
packages/gi-assets-tugraph               |  WARN  The field "resolutions" was found in D:\huiding\gsitem\tugraph\ant2\G6VP\packages\gi-assets-tugraph/package.json. This will not take effect. You should configure "resolutions" at the root of the workspace instead.
Scope: all 22 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. postinstall$ npm run build:all:es
│ > build:all:es
│ > turbo run build:es
│ Error: We detected multiple package managers in your repository: pnpm, npm. Please remove one of them.
└─ Failed in 1.9s at D:\huiding\gsitem\tugraph\ant2\G6VP
 ELIFECYCLE  Command failed with exit code 1.


就是用的 pnpm  install  下载的

**Comment by pomelo-nwu** [comment]
「Error: We detected multiple package managers in your repository: pnpm, npm. Please remove one of them.」

按照报错提示操作 @yubo0923

**Comment by pomelo-nwu** [comment]
@yubo0923  如果你是windows环境，请参考这个issue：https://github.com/antvis/G6VP/issues/44#issuecomment-1341901665
