### ISSUE TITLE
自定义布局，修改edges失效

### ISSUE THREAD

**Issue by yubo0923** [antvis/G6VP#356]
用的2.x 版本   自定义布局后，不能改变edges的节点关系吗

**Comment by pomelo-nwu** [comment]
@yubo0923 没听懂这句话的意思 lol

**Comment by yubo0923** [comment]
@pomelo-nwu  你好，在自定义资产中进行自定义布局   Graphin.registerLayout的execute函数中  加入一些新的node节点后，页面没有生效，什么原因啊
