### ISSUE TITLE
gi-assets-basic 目录下载依赖报错

### ISSUE THREAD

**Issue by yubo0923** [antvis/G6VP#357]
D:\gnt2vp\G6VP\packages\gi-assets-basic>pnpm run build:es

> @antv/gi-assets-basic@2.3.6 build:es D:\huiding\gsitem\gnt2vp\G6VP\packages\gi-assets-basic
> father build

Clean dist directory
Build cjs with babel
Clean lib directory
src\components\ContentContainer\Component.tsx(1,4): error TS1146: Declaration expected.
src\components\ContentContainer\Component.tsx(1,5): error TS2304: Cannot find name 'nocheck'.
src\components\ContentContainer\Component.tsx(17,36): error TS18046: 'item' is of type 'unknown'.
src\components\ContentContainer\Component.tsx(24,38): error TS18046: 'item' is of type 'unknown'.
src\components\ContentContainer\Component.tsx(27,9): error TS18046: 'acc' is of type 'unknown'.
src\components\ContentContainer\Component.tsx(27,13): error TS18046: 'curr' is of type 'unknown'.
src\components\ContentContainer\Component.tsx(27,24): error TS18046: 'curr' is of type 'unknown'.
src\components\ContentContainer\Component.tsx(35,17): error TS2339: Property 'component' does not exist on type 'unknown'.
src\components\ContentContainer\Component.tsx(35,39): error TS2339: Property 'info' does not exist on type 'unknown'.
src\components\ContentContainer\Component.tsx(37,27): error TS18046: 'configMap' is of type 'unknown'.
src\components\LayoutSwitch\Component.tsx(13,12): error TS2503: Cannot find namespace 'NodeJS'.
Transform to cjs for D:/huiding/gsitem/gnt2vp/G6VP/packages/gi-assets-basic/src/index.js
Transform to cjs for D:/huiding/gsitem/gnt2vp/G6VP/packages/gi-assets-basic/src/components/const.js
Transform to cjs for D:/huiding/gsitem/gnt2vp/G6VP/packages/gi-assets-basic/src/components/index.js、

下载依赖报的这个错，怎么处理

**Comment by pomelo-nwu** [comment]
windows下 参考这个 #44
