### ISSUE TITLE
图谱中节点的属性数据是否可更改？

### ISSUE THREAD

**Issue by yikenie** [antvis/G6VP#359]
我想对图谱中某一个属性的值进行修改：
![image](https://github.com/antvis/G6VP/assets/47709014/3f50106b-8cf6-48f7-b949-e69f5808241b)
（这段代码是放在gi-assets-algorithm中的节点重要性算法component.tsx的onAnalyse方法中的）
预想点击分析运行
![image](https://github.com/antvis/G6VP/assets/47709014/8bbacf6d-7323-4925-b8e2-25c9dd555f7b)
显示value值之外把value值放入图中节点的属性中去。
报错显示：Unhandled Rejection (TypeError): Cannot assign to read only property 'FinalScore' of object '#<Object>'。

**Comment by pomelo-nwu** [comment]
> 报错显示：Unhandled Rejection (TypeError): Cannot assign to read only property 'FinalScore' of object '#'。
 
@yikenie  报错提示已经很明显了，context.data 是 useImmer 包裹的 proxy 对象不能修改，因此不能直接操作，你只能updateContext(draft=>{draft.data= newData}) 的方式去修改全局的 data

感觉你不像是前端同学 ^0^
