### ISSUE TITLE
开放-html导出后显示异常

### ISSUE THREAD

**Issue by yikenie** [antvis/G6VP#366]
这是本地显示状态：
![image](https://github.com/antvis/G6VP/assets/47709014/da63e900-7636-4111-82f8-0d8708f3ea2a)
开放导出为html后点击显示：
![image](https://github.com/antvis/G6VP/assets/47709014/4daae7df-dbb5-45de-802b-ea4950674aa7)

**Comment by yangzy0603** [comment]
图标资源访问路径问题，直接本地打开 html 会导致字体图标资源访问为 file 协议，建议本地起服务访问 html
![image](https://github.com/antvis/G6VP/assets/114554589/344a5d22-841b-4f55-b816-57c195eb62c7)

**Comment by pomelo-nwu** [comment]
> 图标资源访问路径问题，直接本地打开 html 会导致字体图标资源访问为 file 协议，建议本地起服务访问 html ![image](https://user-images.githubusercontent.com/114554589/246129218-344a5d22-841b-4f55-b816-57c195eb62c7.png)

Great！ @yikenie 之前这个issue也提到果：https://github.com/antvis/G6VP/issues/332
