### ISSUE TITLE
Cypher 查询不出结果

### ISSUE THREAD

**Issue by ggrgg13** [antvis/G6VP#393]
点击执行查询后一直在空转，不出结果。
![image](https://github.com/antvis/G6VP/assets/123720145/eed41793-2a8b-419d-ab89-5682d2efe093)

**Comment by pomelo-nwu** [comment]
@ggrgg13 用的是什么数据源？

**Comment by ggrgg13** [comment]
json 文件

**Comment by pomelo-nwu** [comment]
@ggrgg13 那当然是不行的啊，上传的 JSON 怎么可能用Cypher查询出来呢，除非这个JSON是上传到图数据库中
