### ISSUE TITLE
zoom specific node

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#396]
Is there a way to zoom on a particular node. (using G6VP or Graphin)

**Comment by pomelo-nwu** [comment]
@RackweLLizm Sure, just use G6 API `graph.focusItem(item, animate, animateCfg)` ,you can see the reference: https://g6.antv.antgroup.com/api/graph-func/transform#graphfocusitemitem-animate-animatecfg

**Comment by RackweLLizm** [comment]
thank you this helped i missed it
