### ISSUE TITLE
执行Cypher 语句查询  报错

### ISSUE THREAD

**Issue by yubo0923** [antvis/G6VP#401]
![2R_H0D ES7DMLFBWVPQQ%SC](https://github.com/antvis/G6VP/assets/114209428/9535cff3-7a86-4878-bd19-c48b9f8f6819)
本地跑的项目 执行Cypher 语句查询  报错
数据源用的官方案例 供应链漏洞分析

**Comment by pomelo-nwu** [comment]
@yubo0923 使用官方提供的数据源：https://insight.antv.antgroup.com/ 都是本地CSV文件，怎么可能使用Cypher查询呢？使用Cypher查询都得是有自己的图数据库

**Comment by yubo0923** [comment]
> @yubo0923 使用官方提供的数据源：https://insight.antv.antgroup.com/ 都是本地CSV文件，怎么可能使用Cypher查询呢？使用Cypher查询都得是有自己的图数据库

谢谢

**Comment by yubo0923** [comment]
![27b9ccaddd780f686872f3673896dba](https://github.com/antvis/G6VP/assets/114209428/649663ca-af91-49bc-8899-dd0ce7f0a4e6)
本地连接neo4j数据库  报错了  有没有案例文档参考的
