### ISSUE TITLE
无法启动gi-httpservice

### ISSUE THREAD

**Issue by wuyueandrew** [antvis/G6VP#423]
master分支
npm 9.7.2

npm install 成功
npm run dev 输出如下

> @antv/gi-httpservice@1.2.0 dev
> egg-bin dev

[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (12ms)
[egg-ts-helper] create typings/config/plugin.d.ts (2ms)
[egg-ts-helper] create typings/app/service/index.d.ts (3ms)
[egg-ts-helper] create typings/app/index.d.ts (0ms)
2023-07-10 13:00:23,452 INFO 2074 [master] node version v20.4.0
2023-07-10 13:00:23,453 INFO 2074 [master] egg version 2.37.0
[egg-ts-helper] create typings/app/controller/index.d.ts (2ms)
[egg-ts-helper] create typings/config/index.d.ts (12ms)
[egg-ts-helper] create typings/config/plugin.d.ts (1ms)
[egg-ts-helper] create typings/app/service/index.d.ts (3ms)
[egg-ts-helper] create typings/app/index.d.ts (1ms)
2023-07-10 13:00:25,235 INFO 2074 [master] agent_worker#1:2096 started (1777ms)
ETCD_HOSTS 127.0.0.1:2379
2023-07-10 13:00:27,026 INFO 2074 [master] egg started on http://127.0.0.1:7001 (3573ms)

但是浏览器访问的时候报错
![image](https://github.com/antvis/G6VP/assets/28866983/36a0739f-a2e7-47db-85fe-71f7c4a08d20)

**Comment by pomelo-nwu** [comment]
@wuyueandrew 只要控制台没有报错就是启动正常的
![image](https://github.com/antvis/G6VP/assets/10703060/72124ee8-fe84-41bd-9d2c-6f0b5457b3b6)

直接访问 127.0.0.1:7001 会访问 https://github.com/antvis/G6VP/blob/master/packages/gi-httpservice/app/view/index.html 
因为这个 index.html 文件很久没更新了，所以报错很正常，后面我处理下。

如果你要访问 web 界面，还需要 `cd gi-site` 然后启动 `npm run start` 通过默认的 127.0.0.1:8000 访问，7001 只是一个 node proxy server

**Comment by wuyueandrew** [comment]
感谢帮助，已解决。
建议官方提供开箱即用的镜像帮助没有前端经验的朋友快速部署。

**Comment by wuyueandrew** [comment]
另外,好像不支持node20，需要降级到node16，提供给有需要的朋友

**Comment by pomelo-nwu** [comment]
> 另外,好像不支持node20，需要降级到node16，提供给有需要的朋友

其实也支持，但是用的是这个sciprt 启动：https://github.com/antvis/G6VP/blob/master/packages/gi-site/package.json#L18
