### ISSUE TITLE
G6VP vs Graphin vs Graph Insight 

### ISSUE THREAD

**Issue by neolee6053** [antvis/G6VP#426]
它们都是同一样的东西？
可以用在angular project 上吗？

**Comment by pomelo-nwu** [comment]
GraphInsight 和 G6VP 是同一个产品，前者是我们的内部孵化项目名，后者是开源项目名。
Graphin 是 G6VP 产品的技术底座，是一个图可视化组件库。
更多详细的介绍可以看：https://www.yuque.com/antv/gi/hl7elg

**Comment by neolee6053** [comment]
> @neolee6053 GraphInsight 和 G6VP 是同一个产品，前者是我们的内部孵化项目名，后者是开源项目名。 Graphin 是 G6VP 产品的技术底座，是一个图可视化组件库。 更多详细的介绍可以看：https://www.yuque.com/antv/gi/hl7elg

谢谢，Graphin 没有angular版？哈哈

**Comment by pomelo-nwu** [comment]
@neolee6053 暂时没有
