### ISSUE TITLE
Using with G6VP "Vite"

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#447]
Hello @pomelo-nwu 

Currently our current project is on the CRA(Create React App) framework, but we are planning to replace it with another framework.

We are planning to migrate our project to **Vite**.

Since we are actively using Graphin and G6VP in our project, I wanted to consult you. Are there any known problems with the Vite? Is this upgrade suitable for G6VP or Graphin use.

In addition, we are looking forward to seeing if there is any development regarding the G6VP v2 release date.

Finally is it possible to use react@18 version for Graphin and G6VP?

Thanks

**Comment by RackweLLizm** [comment]
one more question
If G6VP react 18 update comes, can we use NextJS?

**Comment by pomelo-nwu** [comment]
#379

**Comment by RackweLLizm** [comment]
Vite or NextJS'de npm
