### ISSUE TITLE
G6VP这个项目怎么进行私有化部署

### ISSUE THREAD

**Issue by YongFaGitHub** [antvis/G6VP#483]
G6VP这个项目怎么进行私有化部署，有没有教程怎么部署

**Comment by pomelo-nwu** [comment]
```js
pnpm i 

cd G6VP/packages/gi-site

npm run build 

```
即可得到 G6VP 站点的静态文件

**Comment by YongFaGitHub** [comment]
> build:all:umd
> turbo run build:umd --no-cache

 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
        * no workspace 'packages/gi-httpservice-xxx' found in lockfile


 WARNING  failed to contact turbod. Continuing in standalone mode: connection to turbo daemon process failed. Please ensure the following:
        - the process identified by the pid in the file at C:\Users\newwo\AppData\Local\Temp\turbod\81b66cde594906c1\turbod.pid is not running, and remove C:\Users\newwo\AppData\Local\Temp\turbod\81b66cde594906c1\turbod.pid
        - check the logs at C:\Users\newwo\AppData\Local\turborepo\logs\81b66cde594906c1-G6VP.log
        - the unix domain socket at C:\Users\newwo\AppData\Local\Temp\turbod\81b66cde594906c1\turbod.sock has been removed
        You can also run without the daemon process by passing --no-daemon
• Packages in scope: @antv/gi-assets-advance, @antv/gi-assets-algorithm, @antv/gi-assets-basic, @antv/gi-assets-galaxybase, @antv/gi-assets-graphscope, @antv/gi-assets-hugegraph, @antv/gi-assets-janusgraph, @antv/gi-assets-neo4j
, @antv/gi-assets-scene, @antv/gi-assets-testing, @antv/gi-assets-tugraph, @antv/gi-assets-tugraph-analytics, @antv/gi-cli, @antv/gi-common-components, @antv/gi-httpservice, @antv/gi-portal, @antv/gi-public-data, @antv/gi-sdk, @
antv/gi-sdk-app, @antv/gi-site, @antv/gi-theme-antd, my-custom-server
• Running build:umd in 22 packages
• Remote caching disabled
@antv/gi-sdk-app:build:umd: cache miss, executing 37d7c9b0c190d4e8
@antv/gi-common-components:build:umd: cache miss, executing 6ffd23ae98a72abd
@antv/gi-theme-antd:build:umd: cache miss, executing d97d1aa4c54c82d2
@antv/gi-sdk-app:build:umd: 
@antv/gi-sdk-app:build:umd: > @antv/gi-sdk-app@1.1.1 build:umd D:\工作\G6VP\packages\gi-sdk-app
@antv/gi-sdk-app:build:umd: > webpack --mode production  -c ../../webpack.config.js --env path=/packages/gi-sdk-app
@antv/gi-sdk-app:build:umd: 
@antv/gi-theme-antd:build:umd: 
@antv/gi-theme-antd:build:umd: > @antv/gi-theme-antd@0.6.5 build:umd D:\工作\G6VP\packages\gi-theme-antd
@antv/gi-theme-antd:build:umd: > webpack  --mode production  -c ../../webpack.config.js --env path=/packages/gi-theme-antd
@antv/gi-theme-antd:build:umd: 
@antv/gi-common-components:build:umd: 
@antv/gi-common-components:build:umd: > @antv/gi-common-components@1.3.5 build:umd D:\工作\G6VP\packages\gi-common-components
@antv/gi-common-components:build:umd: > npm run build:es
@antv/gi-common-components:build:umd: 
@antv/gi-theme-antd:build:umd: [webpack-cli] Failed to load 'D:\工作\G6VP\webpack.config.js' config
@antv/gi-sdk-app:build:umd: [webpack-cli] Failed to load 'D:\工作\G6VP\webpack.config.js' config
@antv/gi-theme-antd:build:umd: [webpack-cli] Error: Cannot find module 'webpack-bundle-analyzer'
@antv/gi-theme-antd:build:umd: Require stack:
@antv/gi-theme-antd:build:umd: - D:\工作\G6VP\webpack.config.js
@antv/gi-theme-antd:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\lib\webpack-cli.js
@antv/gi-theme-antd:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\lib\bootstrap.js
@antv/gi-theme-antd:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\bin\cli.js
@antv/gi-theme-antd:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack@5.88.0_webpack-cli@5.0.0\node_modules\webpack\bin\webpack.js
@antv/gi-theme-antd:build:umd:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
@antv/gi-theme-antd:build:umd:     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
@antv/gi-theme-antd:build:umd:     at Module.require (node:internal/modules/cjs/loader:1057:19)
@antv/gi-sdk-app:build:umd: [webpack-cli] Error: Cannot find module 'webpack-bundle-analyzer'
@antv/gi-sdk-app:build:umd: Require stack:
@antv/gi-sdk-app:build:umd: - D:\工作\G6VP\webpack.config.js
@antv/gi-sdk-app:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\lib\webpack-cli.js
@antv/gi-sdk-app:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\lib\bootstrap.js
@antv/gi-sdk-app:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack-cli@5.0.0_webpack@5.88.0\node_modules\webpack-cli\bin\cli.js
@antv/gi-sdk-app:build:umd: - D:\工作\G6VP\node_modules\.pnpm\webpack@5.88.0_webpack-cli@5.0.0\node_modules\webpack\bin\webpack.js
@antv/gi-sdk-app:build:umd:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
@antv/gi-sdk-app:build:umd:     at Function.Module._load (node:internal/modules/cjs/loader:833:27)
@antv/gi-sdk-app:build:umd:     at Module.require (node:internal/modules/cjs/loader:1057:19)
@antv/gi-sdk-app:build:umd:     at require (node:internal/modules/cjs/helpers:103:18)
@antv/gi-theme-antd:build:umd:     at require (node:internal/modules/cjs/helpers:103:18)
@antv/gi-theme-antd:build:umd:     at Object.<anonymous> (D:\工作\G6VP\webpack.config.js:4:34)
@antv/gi-theme-antd:build:umd:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
@antv/gi-theme-antd:build:umd:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
@antv/gi-theme-antd:build:umd:     at Module.load (node:internal/modules/cjs/loader:1033:32)
@antv/gi-theme-antd:build:umd:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
@antv/gi-theme-antd:build:umd:     at Module.require (node:internal/modules/cjs/loader:1057:19) {
@antv/gi-sdk-app:build:umd:     at Object.<anonymous> (D:\工作\G6VP\webpack.config.js:4:34)
@antv/gi-sdk-app:build:umd:     at Module._compile (node:internal/modules/cjs/loader:1155:14)
@antv/gi-sdk-app:build:umd:  ELIFECYCLE  Command failed with exit code 2.
@antv/gi-theme-antd:build:umd:   code: 'MODULE_NOT_FOUND',
@antv/gi-theme-antd:build:umd:  ELIFECYCLE  Command failed with exit code 2.
@antv/gi-sdk-app:build:umd:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
@antv/gi-sdk-app:build:umd:     at Module.load (node:internal/modules/cjs/loader:1033:32)
@antv/gi-sdk-app:build:umd:     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
@antv/gi-sdk-app:build:umd:     at Module.require (node:internal/modules/cjs/loader:1057:19) {
@antv/gi-sdk-app:build:umd:   code: 'MODULE_NOT_FOUND',
@antv/gi-sdk-app:build:umd:   requireStack: [
@antv/gi-sdk-app:build:umd:     'D:\\工作\\G6VP\\webpack.config.js',
@antv/gi-sdk-app:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
@antv/gi-sdk-app:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\lib\\bootstrap.js',
@antv/gi-sdk-app:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\bin\\cli.js',
@antv/gi-sdk-app:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack@5.88.0_webpack-cli@5.0.0\\node_modules\\webpack\\bin\\webpack.js'
@antv/gi-sdk-app:build:umd:   ]
@antv/gi-sdk-app:build:umd: }
@antv/gi-theme-antd:build:umd:   requireStack: [
@antv/gi-theme-antd:build:umd:     'D:\\工作\\G6VP\\webpack.config.js',
@antv/gi-theme-antd:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
@antv/gi-theme-antd:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\lib\\bootstrap.js',
@antv/gi-theme-antd:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack-cli@5.0.0_webpack@5.88.0\\node_modules\\webpack-cli\\bin\\cli.js',
@antv/gi-theme-antd:build:umd:     'D:\\工作\\G6VP\\node_modules\\.pnpm\\webpack@5.88.0_webpack-cli@5.0.0\\node_modules\\webpack\\bin\\webpack.js'
@antv/gi-theme-antd:build:umd:   ]
@antv/gi-theme-antd:build:umd: }
@antv/gi-sdk-app:build:umd:  WARN   Local package.json exists, but node_modules missing, did you mean to install?

**Comment by YongFaGitHub** [comment]
系统是win10
node是v16.18.0
npm是@8.19.2 
运行build命令报错

**Comment by pomelo-nwu** [comment]
@YongFaGitHub 看起来像是 lock文件的问题，检查下是否是master最新代码

**Comment by YongFaGitHub** [comment]
代码已更新最新版本执行报错如下
`D:\work\g6vp2\G6VP\packages\gi-site>npm run build

> @antv/gi-site@2.2.0 prebuild
> node scripts/link.mjs && node --experimental-json-modules scripts/pre-build.mjs

使用示例: pnpm run link <source> [global name]
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@antv/gi-sdk' imported from D:\work\g6vp2\G6VP\packages\gi-site\scripts\pre-build.mjs
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:837:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
`

**Comment by YongFaGitHub** [comment]
使用Linux系统成功打包编译前端页面代码了，
