### ISSUE TITLE
请问G6VP项目能否离线部署

### ISSUE THREAD

**Issue by jesusgod2021** [antvis/G6VP#484]
请问G6VP项目能否离线部署

**Comment by pomelo-nwu** [comment]
```js
pnpm i 

cd G6VP/packages/gi-site

npm run build:docker

```

即可得到 G6VP 站点的静态文件

**Comment by jesusgod2021** [comment]
您好，试了一下，离线状态页面还是无法正常显示。。还是会载入很多在线资源

> 可以的，试试这个命令
> 
> ```js
> pnpm i 
> 
> cd G6VP/packages/gi-site
> 
> npm run build:docker
> ```
> 
> 即可得到 G6VP 站点的静态文件

**Comment by jesusgod2021** [comment]
下了最新版，把静态文件引用在线的地址改成本地下载的，静态文件位置修改正确，可以启动了

**Comment by jesusgod2021** [comment]
您好，再咨询一下，我本地用live server启动静态文件，页面可以正常显示，上传样例数据显示405跨域问题无法跳转页面，请问这个目前是只能离线单机部署是吗

**Comment by pomelo-nwu** [comment]
@jesusgod2021 支持的，你研究下 gi-site 的 docker file 文件，目前我们在阿里云上都有部署的，云端存储走的是etcd方案

**Comment by jesusgod2021** [comment]
> @jesusgod2021 支持的，你研究下 gi-site 的 docker file 文件，目前我们在阿里云上都有部署的，云端存储走的是etcd方案

好的好的感谢

**Comment by pomelo-nwu** [comment]
@jesusgod2021 好的，如果觉得 G6VP 对你的业务项目有帮助，还望点个 star 支持下
