### ISSUE TITLE
pnpm install报错

### ISSUE THREAD

**Issue by FrankBGao** [antvis/G6VP#526]
![image](https://github.com/antvis/G6VP/assets/20436775/216c2ec9-4359-487d-b566-8e55e34fd132)
能帮忙看下，这个报错是什么原因吗，装不上

**Comment by pomelo-nwu** [comment]
@FrankBGao windows 环境报错情况参考这个：https://github.com/antvis/G6VP/issues/44#issuecomment-1341901665
