### ISSUE TITLE
updateData and Layout not refresh

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#534]
Hello @pomelo-nwu 

I am currently using context.graph to update G6VP Data. 

Example Scenario; 
There are 10 nodes in the current graph. I am adding new data to these existing 10 nodes. The number of nodes increases to 50 and I want all G6VP to show the new data together with the old ones. 

https://www.yuque.com/antv/gi/crpanx 

I update rawData and Data with useContext. I also update the SchemaData of the newly added data. All are Dynamic. 

But FilterPanel etc. other components are not updated with newly added data. 

I solved this myself like this. 

```
context.updateContext((draft: any) => {
      draft.schemaData.edges = [...draft.schemaData.edges, ...tmpEdgeSchema]
      draft.schemaData.nodes = [...draft.schemaData.nodes, ...tmpNodeSchema]
    })

      context.graph.addItems(nodeTmpArrays);
      context.graph.addItems(edgeTmpArrays);
      let xc = context.graph.save();
 
      context.updateData(xc);
```

This method works. But is it possible to get a feedback about its performance and accuracy? 

Finally, when I run the updateData command, new data is added to the canvas and the layout is re-run, which causes the appearance of the current canvas to change every time data is added, can I disable this, that is, data is added to the canvas but the layout is not run? so that the user's work is not distorted when the layout changes. 

Thank you very much

**Comment by pomelo-nwu** [comment]
@RackweLLizm you can refer to QueryNeighbors: https://github.com/antvis/G6VP/blob/master/packages/gi-assets-basic/src/components/NeighborsQuery/Component.tsx#L112
