### ISSUE TITLE
本地部署后， 连接neo4j的saas服务报错

### ISSUE THREAD

**Issue by Hisnameandhe** [antvis/G6VP#552]
<img width="1490" alt="image" src="https://github.com/antvis/G6VP/assets/144974166/2137a15e-11ce-42f1-b0cb-d66569d7189f">

<img width="1892" alt="image" src="https://github.com/antvis/G6VP/assets/144974166/bd95d042-7029-4666-8afb-5de4fdbb86a0">

**Comment by pomelo-nwu** [comment]
@Hisnameandhe 升级版本"neo4j-driver": "^5.12.0" 即可，详见：https://github.com/antvis/G6VP/pull/544

**Comment by Hisnameandhe** [comment]
赞
