### ISSUE TITLE
🐛bug: render issue of neo4j schema

### ISSUE THREAD

**Issue by nylqd** [antvis/G6VP#558]
current schema canvas do not have edges, maybe another data process problem?
<img width="1123" alt="image" src="https://github.com/antvis/G6VP/assets/3632490/1f497cc8-cb24-4996-9494-a54304898046">

expected as follow
<img width="1090" alt="image" src="https://github.com/antvis/G6VP/assets/3632490/3473374f-bcf1-4fd9-a51d-481e65afd139">

**Comment by pomelo-nwu** [comment]
@nylqd t seems to be an issue with the EngineServer component:https://github.com/antvis/G6VP/blob/master/packages/gi-assets-neo4j/src/services/Engine.tsx#L1

**Comment by pomelo-nwu** [comment]
https://github.com/antvis/G6VP/blob/master/packages/gi-sdk/src/components/EngineServer/LoadGraph.tsx#L148 
because I have switched to the pref/sdk-valtio branch for the upgrade of G6 5.0, which involves a lot of changes, I haven't switched to the master branch to investigate the issue for now. If possible, I would appreciate your help in resolving it.

**Comment by nylqd** [comment]
> [`master`/packages/gi-sdk/src/components/EngineServer/LoadGraph.tsx#L148](https://github.com/antvis/G6VP/blob/master/packages/gi-sdk/src/components/EngineServer/LoadGraph.tsx?rgh-link-date=2023-11-21T12%3A38%3A09Z#L148) because I have switched to the pref/sdk-valtio branch for the upgrade of G6 5.0, which involves a lot of changes, I haven't switched to the master branch to investigate the issue for now. If possible, I would appreciate your help in resolving it.

@pomelo-nwu it seems indeed have bug in getSchemaGraph, i will do some digging around.
<img width="576" alt="image" src="https://github.com/antvis/G6VP/assets/3632490/eb27ca4e-24c2-4d37-9e1f-b214d3e7a71d">

**Comment by pomelo-nwu** [comment]
@nylqd Considering that different graph database will use the same EngineServer component, I am more inclined towards the second solution.
