### ISSUE TITLE
表格模式的分屏按钮提供配置选择是否展示

### ISSUE THREAD

**Issue by yangzy0603** [antvis/G6VP#57]
以 SDK 的方式集成到项目中去时，表格模式的分屏页面需要集成方自己集成实现，期望分屏按钮可以由用户自己控制是否展示，在确认集成了分屏页面后再透出分屏按钮

**Comment by pomelo-nwu** [comment]
@yangzy0603 好建议，后面我抽取下

**Comment by yangzy0603** [comment]
好的，我处理下
