### ISSUE TITLE
关于组件资产问题

### ISSUE THREAD

**Issue by SINK-MASTER** [antvis/G6VP#589]
在**tugraph-db-browser**中请问以下组件在哪里可以找到

'TuGraphAttributesFilter'
'TuGraphBack'
'TuGraphDownload'
'TuGraphLockNode'
'TuGraphPathQuery'
'TuGraphPropertiesPanel'
'TuGraphStatisticsFilter'
'TuGraphStyleSetting'

**Comment by pomelo-nwu** [comment]
@SINK-MASTER https://github.com/TuGraph-family/gi-assets-tugraph-db/blob/master/src/components/index.ts
