### ISSUE TITLE
gi-panel-div bug

### ISSUE THREAD

**Issue by RackweLLizm** [antvis/G6VP#79]
![issue](https://user-images.githubusercontent.com/52632318/207887104-c929ac2f-9a0d-44c7-a58a-89919cc3e894.png)

Hello; While exporting GraphInsight SDK, I extract it as npm package from 提供 NPM 包，支持 Tree Shaking，原生集成到 React 项目中. After making the necessary additions to my project, on the right when first opened 属性面板
(gi-panel-div)
part stays open all the time and does not close. I checked the version differences, I was using antd 15 from the beginning, then even though I downgraded to 14, the same problem persisted. All other packages are same as sample code in codesandbox including graphin. I would be very happy if you could help me with the problem.

**Comment by pomelo-nwu** [comment]
@BoyYangzai 跟进一下

**Comment by BoyYangzai** [comment]
线上环境的`属性面板`表现也不符合预期
